=== Weespies/composure/src/main/resources/data/assets.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="assets">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="asset" type="trait" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="trait">
		<xsd:sequence>
			<xsd:element name="description" type="xsd:string" minOccurs="0" maxOccurs="1"/>
		</xsd:sequence>
		<xsd:attribute name="name" use="required" />
		<xsd:attribute name="focus" use="optional" />
		<xsd:attribute name="skill" use="optional" />
		<xsd:attribute name="type" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="MAJOR" />
					<xsd:enumeration value="MINOR" />
					<xsd:enumeration value="BOTH" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>

	</xsd:complexType>

</xsd:schema>

=== Weespies/composure/src/main/resources/data/assets.xml
<?xml version="1.0" encoding="UTF-8"?>
<assets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="assets.xsd">

	<asset name="Allure" type="BOTH" focus="any">
		<description>
		With minor allure you gain a +2 step Skill die bonuson all actions keyed to appearance, such as seduction,
		negotiation, persuasion or winning beauty pageants.  If you are gorgeous enough to have major Allure, whenever
		you spent plot points on these actions you spend an additional 2 free plotpoints.
		</description>
	</asset>
	<asset name="Athlete" type="BOTH" skill="Athletics"/>
	<asset name="Fightin' Type" type="MAJOR"/>
	<asset name="Friends in Low Places" type="MINOR"/>
	<asset name="Friends in High Places" type="MINOR"/>
	<asset name="High Born" type="MAJOR"/>
	<asset name="Healthy as a Horse" type="MAJOR"/>
	<asset name="Heavy Tolerance" type="MINOR"/>
	<asset name="Highly Educated" type="MINOR"/>
	<asset name="Intimidating Manner" type="MINOR"/>
	<asset name="Leadership" type="BOTH"/>
	<asset name="Lightnin' Reflexes" type="MAJOR"/>
	<asset name="Math Whiz" type="MINOR"/>
	<asset name="Unarmed Combat Expert" type="MINOR"/>
	<asset name="Mechanical Empathy" type="MINOR"/>
	<asset name="Military Rank" type="MINOR"/>
	<asset name="Moneyed Individual" type="MAJOR"/>
	<asset name="Nature Lover" type="MINOR"/>
	<asset name="Nose for Trouble" type="BOTH"/>
	<asset name="Spiritual" type="BOTH"/>
	<asset name="Sharp Sense" type="MINOR" focus="Smell|Touch|Sight|Taste|Hearing"/>
	<asset name="Steady Calm" type="BOTH"/>
	<asset name="Optimistic" type="MINOR"/>
	<asset name="Talented" type="BOTH" skill="any"/>
	<asset name="Things Go Smooth" type="BOTH"/>
	<asset name="Total Recall" type="MAJOR"/>
	<asset name="Tough as Nails" type="BOTH"/>
	<asset name="Trustworthy Gut" type="BOTH"/>
	<asset name="Two-Fisted" type="MAJOR"/>
	<asset name="Walking Timepiece" type="MINOR"/>
	<asset name="Wears a Badge" type="BOTH"/>
</assets>
