=== Weespies/composure/src/main/resources/data/rangedWeapons.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="rangedList">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="ranged" type="ranged" minOccurs="0"
					maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="ranged">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="cost" type="xsd:float" use="optional"/>
		<xsd:attribute name="weight" type="xsd:float" use="optional"/>
		<xsd:attribute name="range" type="xsd:float" use="optional"/>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="damage" type="xsd:string" use="required"/>
		<xsd:attribute name="skill" type="xsd:string" use="optional"/>
		<xsd:attribute name="clip" type="xsd:int" use="required"/>
		<xsd:attribute name="rate" type="xsd:float" use="required"/>
		<xsd:attribute name="availability">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="E" />
					<xsd:enumeration value="C" />
					<xsd:enumeration value="R" />
					<xsd:enumeration value="I" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	
</xsd:schema>

=== Weespies/composure/src/main/resources/data/rangedweapons.xml
<?xml version="1.0" encoding="UTF-8"?>
<rangedList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rangedWeapons.xsd">

	<ranged name="Bow" chance="90" damage="d4 W" cost="6" weight="8" availability="E" range="70" rate="1" clip="1" type="Ranged" skill="Ranged Weapons,Bows" max="1"/>
	<ranged name="Crossbow" chance="90" damage="d4 W" cost="8" weight="13" availability="C" range="150" rate="0.5" clip="1" type="Ranged" skill="Ranged Weapons,Crossbows" max="1" />
	<ranged name="Explsovie Projector" chance="10" damage="*" cost="106" weight="12" availability="I" range="40" rate="1" clip="8" type="Ranged" skill="Heavy Weapons,Grenades" max="1" />
	<ranged name="Disruptor Pistol" chance="90" damage="d8 W" cost="18" weight="2" availability="E" range="100" rate="3" clip="20" type="Ranged" skill="Guns,Pistols" max="2" />
	<ranged name="Phaser Pistol" chance="20" damage="d2 to D8 W/S" cost="18" weight="2" availability="E" range="100" rate="3" clip="50" type="Ranged" skill="Guns,Pistols" max="2" /
	<ranged name="Kinetic Pistol" chance="10" damage="d6 W" cost="18" weight="2" availability="E" range="100" rate="3" clip="8" type="Ranged" skill="Guns,Pistols" max="2" />
	
	<ranged name="Disruptor Rifle" chance="90" damage="d12 W" cost="18" weight="2" availability="E" range="100" rate="3" clip="50" type="Ranged" skill="Guns,Pistols" max="2" />
	<ranged name="Phaser Rifle" chance="20" damage="d6 to D20 W/S" cost="18" weight="2" availability="E" range="100" rate="3" clip="200" type="Ranged" skill="Guns,Pistols" max="2" /
	<ranged name="Kinetic Rifle" chance="10" damage="d8 W" cost="18" weight="2" availability="E" range="100" rate="3" clip="8" type="Ranged" skill="Guns,Pistols" max="2" />
	
</rangedList>
