=== Weespies/composure/src/main/resources/data/skills.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="skills">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="skill" type="skill" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:complexType name="skill">	
		<xsd:sequence>
			<xsd:element name="specialty" type="specialty"
				minOccurs="1" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="name" use="required"/>
		<xsd:attribute name="skilledOnly" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="yes" />
					<xsd:enumeration value="no" />
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="specialty">
		<xsd:attribute name="child" use="required" />
	</xsd:complexType>
	
</xsd:schema>

=== Weespies/composure/src/main/resources/data/skills.xml
<?xml version="1.0" encoding="UTF-8"?>

<skills xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="skills.xsd">        
	<skill name="Animal Handling">
		<specialty child="Animal Training"/>
		<specialty child="Riding"/>
		<specialty child="Vetinary"/>
		<specialty child="Zoology"/>
	</skill>
	<skill name="Artistry">
		<specialty child="Appraisal"/>
		<specialty child="Cooking"/>
		<specialty child="Forgery"/>
		<specialty child="Painting"/>
		<specialty child="Photography"/>
		<specialty child="Poetry"/>
		<specialty child="Song Writing"/>
		<specialty child="Sculpting"/>
		<specialty child="Writing"/>
	</skill>
	<skill name="Athletics">
		<specialty child="Climbing"/>
		<specialty child="Contortion"/>
		<specialty child="Dodge"/>
		<specialty child="Juggling"/>
		<specialty child="Jumping"/>
		<specialty child="Gymnastics"/>
		<specialty child="Parachuting"/>
		<specialty child="Parasailing"/>
		<specialty child="Pole Vaulting"/>
		<specialty child="Riding"/>
		<specialty child="Running"/>
		<specialty child="Swimming"/>
		<specialty child="Weight Lifting"/>
	</skill>
	<skill name="Covert">
		<specialty child="Camoflauge"/>
		<specialty child="Disable Devices"/>
		<specialty child="Forgery"/>
		<specialty child="Infiltration"/>
		<specialty child="Open Locks"/>
		<specialty child="Sabotage"/>
		<specialty child="Sleight of Hand"/>
		<specialty child="Stealth"/>
		<specialty child="Streetwise"/>
		<specialty child="Surveillance"/>
	</skill>
	<skill name="Craft">
		<specialty child="Architecture"/>
		<specialty child="Blacksmithing"/>
		<specialty child="Carpentry"/>
		<specialty child="Cooking"/>
		<specialty child="Leatherworking"/>
		<specialty child="Metalworking"/>
		<specialty child="Pottery"/>
		<specialty child="Sewing"/>
	</skill>
	<skill name="Discipline">
		<specialty child="Concentration"/>
		<specialty child="Interrogation"/>
		<specialty child="Intimidation"/>
		<specialty child="Leadership"/>
		<specialty child="Mental Resistance"/>
		<specialty child="Morale"/>
	</skill>
	<skill name="Guns">
		<specialty child="Single Handed Kinetic"/>
		<specialty child="Double Handed Kinetic"/>
		<specialty child="Disrutpors"/>
		<specialty child="Phasers"/>
		<specialty child="Blasters"/>
	</skill>
	<skill name="Heavy Weapons">
		<specialty child="Ship Torpedo"/>
		<specialty child="Ship Beam"/>
		<specialty child="Ship Projectiles"/>
		<specialty child="Ancient Weapons"/>
		<specialty child="Repair Heavy Weapons"/>
		<specialty child="Rocket Launchers"/>
	</skill>
	<skill name="Influence">
		<specialty child="Administration"/>
		<specialty child="Barter"/>
		<specialty child="Bureaucracy"/>
		<specialty child="Conversation"/>
		<specialty child="Counseling"/>
		<specialty child="Interrogation"/>
		<specialty child="Intimidation"/>
		<specialty child="Leadership"/>
		<specialty child="Marketing"/>
		<specialty child="Persuasion"/>
		<specialty child="Politics"/>
		<specialty child="Seduction"/>
		<specialty child="Streetwise"/>
	</skill>
	<skill name="Knowledge">
		<specialty child="Appraisal"/>
		<specialty child="Cultures"/>
		<specialty child="History"/>
		<specialty child="Law"/>
		<specialty child="Literature"/>
		<specialty child="Philosophy"/>
		<specialty child="Religion"/>
		<specialty child="Sports"/>
	</skill>
	<skill name="Linguist" skilledOnly="true">
		<specialty child="Terran"/>
		<specialty child="Klingon"/>
		<specialty child="Romulan"/>
		<specialty child="Vulcan"/>
		<specialty child="Andoran"/>
		<specialty child="Saurian"/>
		<specialty child="Tholian"/>
		<specialty child="Bajoran"/>
		<specialty child="Cardasian"/>
	</skill>
	<skill name="Mechanical Engineering" skilledOnly="true">
		<specialty child="Create Mechanical Devices"/>
		<specialty child="Machinery Maintenance"/>
		<specialty child="Mechanical Repairs"/>
		<specialty child="Fix Mechanical Security Systems"/>
		<specialty child="Plumbing"/>
		<specialty child="Starship Engineering"/>
	</skill>
	<skill name="Medical Expertise" skilledOnly="true">
		<specialty child="Dentistry"/>
		<specialty child="First Aid"/>
		<specialty child="Field Medic"/>
		<specialty child="Forensics"/>
		<specialty child="General Practice"/>
		<specialty child="Genetics"/>
		<specialty child="Internal Medicine"/>
		<specialty child="Neurology"/>
		<specialty child="Pharmaceuticals"/>
		<specialty child="Physiology"/>
		<specialty child="Psychiatry"/>
		<specialty child="Rehabilitation"/>
		<specialty child="Surgery"/>
		<specialty child="Toxicology"/>
		<specialty child="Vetinary Medicine"/>
		
	</skill>
	<skill name="Melee Weapon Combat">
		<specialty child="Clubs"/>
		<specialty child="Knives"/>
		<specialty child="Melee Weaponsmithing"/>
		<specialty child="Nunchaku"/>
		<specialty child="Pole Arms"/>
		<specialty child="Swords"/>
		<specialty child="Bat'leth"/>
		<specialty child="Whips"/>
	</skill>
	<skill name="Perception">
		<specialty child="Deduction"/>
		<specialty child="Empathy"/>
		<specialty child="Gambling"/>
		<specialty child="Hearing"/>
		<specialty child="Intuition"/>
		<specialty child="Investigation"/>
		<specialty child="Read Lips"/>
		<specialty child="Search"/>
		<specialty child="Sight"/>
		<specialty child="Smell"/>
		<specialty child="Tactics"/>
		<specialty child="Taste"/>
		<specialty child="Tracking"/>
	</skill>
	<skill name="Performance">
		<specialty child="Acting"/>
		<specialty child="Costuming"/>
		<specialty child="Dancing"/>
		<specialty child="Impersonation"/>
		<specialty child="Keyboard Instruments"/>
		<specialty child="Mimicry"/>
		<specialty child="Oratory"/>
		<specialty child="Percussion Instruments"/>
		<specialty child="Rock and Roll"/>
		<specialty child="Singing"/>
		<specialty child="Stringed Instruments"/>
		<specialty child="Wind Instruments"/>
	</skill>
	<skill name="Pilot" skilledOnly="true">
		<specialty child="Aerial Navigation"/>
		<specialty child="Astrogation"/>
		<specialty child="Astronomy"/>
		<specialty child="Astrophysics"/>
		<specialty child="Shuttles"/>
		<specialty child="Starship Helming"/>
		<specialty child="Space Survival"/>
	</skill>
	<skill name="Planetary Vehicle">
		<specialty child="Aquatic Navigation"/>
		<specialty child="Watercraft"/>
		<specialty child="Atmospheric Craft"/>
		<specialty child="Ground Vehicle Repair"/>
		<specialty child="Industrial Vehicles"/>
		<specialty child="Land Navigation"/>
		<specialty child="Large Ground Transports"/>
		<specialty child="Military Combat Vehicles"/>
	</skill>
	<skill name="Military Tactics">
		<specialty child="Spaace fleet combat"/>
		<specialty child="Ground assault"/>
		<specialty child="Ground special forces"/>
		<specialty child="Covert Infiltration"/>
		<specialty child="Famous Tactics (Racial)"/>
		<specialty child="Ground Defensive Tactics"/>
		<specialty child="Force Motivation"/>
		<specialty child="The Great Warriors"/>
	</skill>
	<skill name="Ranged Weapons">
		<specialty child="Blowguns"/>
		<specialty child="Bows"/>
		<specialty child="Crossbows"/>
		<specialty child="Darts"/>
		<specialty child="Grenades"/>
		<specialty child="Javelin"/>
		<specialty child="Ranged Weaponsmithing"/>
		<specialty child="Slings"/>
		<specialty child="Throwing Axes"/>
		<specialty child="Throwing Knives"/>
	</skill>
	<skill name="Scientific Expertise" skilledOnly="true">
		<specialty child="Planetary Sciences"/>
		<specialty child="Astronomy"/>
		<specialty child="Historical Sciences"/>
		<specialty child="Biology"/>
		<specialty child="Mathematical Sciences"/>
		<specialty child="Warp Sciences"/>
		<specialty child="Quantum Sciences"/>
		<specialty child="Temporal Sciences"/>
	</skill>
	<skill name="Survival">
		<specialty child="Aerial"/>
		<specialty child="Aquatic"/>
		<specialty child="Generical Navigation"/>
		<specialty child="Land Survival"/>
		<specialty child="Nature"/>
		<specialty child="Space"/>
	</skill>
	<skill name="Technical Engineering" skilledOnly="true">
		<specialty child="Communications Systems"/>
		<specialty child="Computer Systems"/>
		<specialty child="Hacking"/>
		<specialty child="Create/Alter Technical Devices"/>
		<specialty child="Demolitions"/>
		<specialty child="Electronics"/>
		<specialty child="Warp Systems"/>
		<specialty child="Impulse Systems"/>
		<specialty child="Transporter Systems"/>
		<specialty child="Weapon Systems"/>
		<specialty child="Technical Security Systems"/>
	</skill>
	<skill name="Unarmed Combat">
		<specialty child="Racial Martial Arts"/>
		<specialty child="Wrestling"/>
	</skill>
</skills>
